// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkgpnqrtoiotiiyibfwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrZ3BucXJ0b2lvdGlpeWliZnd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTAyNzMsImV4cCI6MjA2MjEyNjI3M30.A5K29uKvQEJVuAhwQac2Hhka434f43nTWjG3MqsZlwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);