// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylemfwxcpknocbcpeiev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsZW1md3hjcGtub2NiY3BlaWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTgyMjMsImV4cCI6MjA2MTg3NDIyM30.sVWnfIkPtr146CZlC5-lzTWJMNa22MVKrvIJYyr9v3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);